drop extension if exists "pg_net";

create type "public"."visibility_type" as enum ('private', 'public');


  create table "public"."Todo" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text default 'Sortir le chien'::text,
    "status" text default 'todo'::text
      );



  create table "public"."exquisite_corpse_config" (
    "id" uuid not null default gen_random_uuid(),
    "workshop_id" uuid,
    "visibility" public.visibility_type default 'public'::public.visibility_type,
    "max_participants" integer,
    "iterations_count" integer default 1,
    "closes_at" timestamp with time zone,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."exquisite_corpse_config" enable row level security;


  create table "public"."presences" (
    "id" uuid not null default gen_random_uuid(),
    "writing_workshop_id" uuid,
    "user_id" uuid,
    "last_active_at" timestamp with time zone default now(),
    "created_at" timestamp with time zone default now(),
    "guest_id" uuid default gen_random_uuid()
      );


alter table "public"."presences" enable row level security;


  create table "public"."segments" (
    "id" uuid not null default gen_random_uuid(),
    "workshop_id" uuid,
    "text" text,
    "guest_id" uuid,
    "user_id" uuid,
    "round" integer,
    "position" integer,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."segments" enable row level security;


  create table "public"."users" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone default now()
      );


alter table "public"."users" enable row level security;


  create table "public"."workshop_access" (
    "id" uuid not null default gen_random_uuid(),
    "workshop_id" uuid,
    "type" text,
    "code" text,
    "email" text,
    "created_at" timestamp with time zone default now(),
    "whatsapp_link" text
      );


alter table "public"."workshop_access" enable row level security;


  create table "public"."writing_workshops" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "prompt" text,
    "title" text,
    "status" text default 'draft'::text,
    "start_time" timestamp with time zone default (now() AT TIME ZONE 'utc'::text),
    "end_time" timestamp with time zone default (now() AT TIME ZONE 'utc'::text),
    "max_participants" integer default 100,
    "created_by" uuid default auth.uid(),
    "current_turn_user_id" uuid
      );


alter table "public"."writing_workshops" enable row level security;

CREATE UNIQUE INDEX "Todo_pkey" ON public."Todo" USING btree (id);

CREATE UNIQUE INDEX exquisite_corpse_config_pkey ON public.exquisite_corpse_config USING btree (id);

CREATE UNIQUE INDEX presences_pkey ON public.presences USING btree (id);

CREATE UNIQUE INDEX segments_pkey ON public.segments USING btree (id);

CREATE UNIQUE INDEX sessions_pkey ON public.writing_workshops USING btree (id);

CREATE UNIQUE INDEX unique_workshop_id_by_access ON public.workshop_access USING btree (workshop_id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX workshop_access_pkey ON public.workshop_access USING btree (id);

alter table "public"."Todo" add constraint "Todo_pkey" PRIMARY KEY using index "Todo_pkey";

alter table "public"."exquisite_corpse_config" add constraint "exquisite_corpse_config_pkey" PRIMARY KEY using index "exquisite_corpse_config_pkey";

alter table "public"."presences" add constraint "presences_pkey" PRIMARY KEY using index "presences_pkey";

alter table "public"."segments" add constraint "segments_pkey" PRIMARY KEY using index "segments_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."workshop_access" add constraint "workshop_access_pkey" PRIMARY KEY using index "workshop_access_pkey";

alter table "public"."writing_workshops" add constraint "sessions_pkey" PRIMARY KEY using index "sessions_pkey";

alter table "public"."exquisite_corpse_config" add constraint "exquisite_corpse_config_iterations_count_check" CHECK ((iterations_count > 0)) not valid;

alter table "public"."exquisite_corpse_config" validate constraint "exquisite_corpse_config_iterations_count_check";

alter table "public"."exquisite_corpse_config" add constraint "exquisite_corpse_config_max_participants_check" CHECK ((max_participants > 0)) not valid;

alter table "public"."exquisite_corpse_config" validate constraint "exquisite_corpse_config_max_participants_check";

alter table "public"."exquisite_corpse_config" add constraint "exquisite_corpse_config_workshop_id_fkey" FOREIGN KEY (workshop_id) REFERENCES public.writing_workshops(id) ON DELETE CASCADE not valid;

alter table "public"."exquisite_corpse_config" validate constraint "exquisite_corpse_config_workshop_id_fkey";

alter table "public"."exquisite_corpse_config" add constraint "must_have_limit_or_deadline" CHECK (((max_participants IS NOT NULL) <> (closes_at IS NOT NULL))) not valid;

alter table "public"."exquisite_corpse_config" validate constraint "must_have_limit_or_deadline";

alter table "public"."presences" add constraint "presences_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE not valid;

alter table "public"."presences" validate constraint "presences_user_id_fkey";

alter table "public"."presences" add constraint "presences_writing_workshop_id_fkey" FOREIGN KEY (writing_workshop_id) REFERENCES public.writing_workshops(id) ON DELETE CASCADE not valid;

alter table "public"."presences" validate constraint "presences_writing_workshop_id_fkey";

alter table "public"."segments" add constraint "segments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE not valid;

alter table "public"."segments" validate constraint "segments_user_id_fkey";

alter table "public"."segments" add constraint "segments_workshop_id_fkey" FOREIGN KEY (workshop_id) REFERENCES public.writing_workshops(id) ON DELETE CASCADE not valid;

alter table "public"."segments" validate constraint "segments_workshop_id_fkey";

alter table "public"."segments" add constraint "user_or_guest" CHECK (((((user_id IS NOT NULL))::integer + ((guest_id IS NOT NULL))::integer) = 1)) not valid;

alter table "public"."segments" validate constraint "user_or_guest";

alter table "public"."workshop_access" add constraint "check_code_email_logic" CHECK ((((type = 'code'::text) AND (email IS NULL) AND (whatsapp_link IS NULL) AND (code IS NOT NULL)) OR ((type = 'email_invite'::text) AND (code IS NULL) AND (whatsapp_link IS NULL) AND (email IS NOT NULL)) OR ((type = 'whatsapp_link'::text) AND (code IS NULL) AND (email IS NULL) AND (whatsapp_link IS NOT NULL)))) not valid;

alter table "public"."workshop_access" validate constraint "check_code_email_logic";

alter table "public"."workshop_access" add constraint "unique_workshop_id_by_access" UNIQUE using index "unique_workshop_id_by_access";

alter table "public"."workshop_access" add constraint "workshop_access_type_check" CHECK ((type = ANY (ARRAY['code'::text, 'email_invite'::text, 'whatsapp_link'::text]))) not valid;

alter table "public"."workshop_access" validate constraint "workshop_access_type_check";

alter table "public"."workshop_access" add constraint "workshop_access_workshop_id_fkey" FOREIGN KEY (workshop_id) REFERENCES public.writing_workshops(id) ON DELETE CASCADE not valid;

alter table "public"."workshop_access" validate constraint "workshop_access_workshop_id_fkey";

grant delete on table "public"."Todo" to "anon";

grant insert on table "public"."Todo" to "anon";

grant references on table "public"."Todo" to "anon";

grant select on table "public"."Todo" to "anon";

grant trigger on table "public"."Todo" to "anon";

grant truncate on table "public"."Todo" to "anon";

grant update on table "public"."Todo" to "anon";

grant delete on table "public"."Todo" to "authenticated";

grant insert on table "public"."Todo" to "authenticated";

grant references on table "public"."Todo" to "authenticated";

grant select on table "public"."Todo" to "authenticated";

grant trigger on table "public"."Todo" to "authenticated";

grant truncate on table "public"."Todo" to "authenticated";

grant update on table "public"."Todo" to "authenticated";

grant delete on table "public"."Todo" to "service_role";

grant insert on table "public"."Todo" to "service_role";

grant references on table "public"."Todo" to "service_role";

grant select on table "public"."Todo" to "service_role";

grant trigger on table "public"."Todo" to "service_role";

grant truncate on table "public"."Todo" to "service_role";

grant update on table "public"."Todo" to "service_role";

grant delete on table "public"."exquisite_corpse_config" to "anon";

grant insert on table "public"."exquisite_corpse_config" to "anon";

grant references on table "public"."exquisite_corpse_config" to "anon";

grant select on table "public"."exquisite_corpse_config" to "anon";

grant trigger on table "public"."exquisite_corpse_config" to "anon";

grant truncate on table "public"."exquisite_corpse_config" to "anon";

grant update on table "public"."exquisite_corpse_config" to "anon";

grant delete on table "public"."exquisite_corpse_config" to "authenticated";

grant insert on table "public"."exquisite_corpse_config" to "authenticated";

grant references on table "public"."exquisite_corpse_config" to "authenticated";

grant select on table "public"."exquisite_corpse_config" to "authenticated";

grant trigger on table "public"."exquisite_corpse_config" to "authenticated";

grant truncate on table "public"."exquisite_corpse_config" to "authenticated";

grant update on table "public"."exquisite_corpse_config" to "authenticated";

grant delete on table "public"."exquisite_corpse_config" to "service_role";

grant insert on table "public"."exquisite_corpse_config" to "service_role";

grant references on table "public"."exquisite_corpse_config" to "service_role";

grant select on table "public"."exquisite_corpse_config" to "service_role";

grant trigger on table "public"."exquisite_corpse_config" to "service_role";

grant truncate on table "public"."exquisite_corpse_config" to "service_role";

grant update on table "public"."exquisite_corpse_config" to "service_role";

grant delete on table "public"."presences" to "anon";

grant insert on table "public"."presences" to "anon";

grant references on table "public"."presences" to "anon";

grant select on table "public"."presences" to "anon";

grant trigger on table "public"."presences" to "anon";

grant truncate on table "public"."presences" to "anon";

grant update on table "public"."presences" to "anon";

grant delete on table "public"."presences" to "authenticated";

grant insert on table "public"."presences" to "authenticated";

grant references on table "public"."presences" to "authenticated";

grant select on table "public"."presences" to "authenticated";

grant trigger on table "public"."presences" to "authenticated";

grant truncate on table "public"."presences" to "authenticated";

grant update on table "public"."presences" to "authenticated";

grant delete on table "public"."presences" to "service_role";

grant insert on table "public"."presences" to "service_role";

grant references on table "public"."presences" to "service_role";

grant select on table "public"."presences" to "service_role";

grant trigger on table "public"."presences" to "service_role";

grant truncate on table "public"."presences" to "service_role";

grant update on table "public"."presences" to "service_role";

grant delete on table "public"."segments" to "anon";

grant insert on table "public"."segments" to "anon";

grant references on table "public"."segments" to "anon";

grant select on table "public"."segments" to "anon";

grant trigger on table "public"."segments" to "anon";

grant truncate on table "public"."segments" to "anon";

grant update on table "public"."segments" to "anon";

grant delete on table "public"."segments" to "authenticated";

grant insert on table "public"."segments" to "authenticated";

grant references on table "public"."segments" to "authenticated";

grant select on table "public"."segments" to "authenticated";

grant trigger on table "public"."segments" to "authenticated";

grant truncate on table "public"."segments" to "authenticated";

grant update on table "public"."segments" to "authenticated";

grant delete on table "public"."segments" to "service_role";

grant insert on table "public"."segments" to "service_role";

grant references on table "public"."segments" to "service_role";

grant select on table "public"."segments" to "service_role";

grant trigger on table "public"."segments" to "service_role";

grant truncate on table "public"."segments" to "service_role";

grant update on table "public"."segments" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

grant delete on table "public"."workshop_access" to "anon";

grant insert on table "public"."workshop_access" to "anon";

grant references on table "public"."workshop_access" to "anon";

grant select on table "public"."workshop_access" to "anon";

grant trigger on table "public"."workshop_access" to "anon";

grant truncate on table "public"."workshop_access" to "anon";

grant update on table "public"."workshop_access" to "anon";

grant delete on table "public"."workshop_access" to "authenticated";

grant insert on table "public"."workshop_access" to "authenticated";

grant references on table "public"."workshop_access" to "authenticated";

grant select on table "public"."workshop_access" to "authenticated";

grant trigger on table "public"."workshop_access" to "authenticated";

grant truncate on table "public"."workshop_access" to "authenticated";

grant update on table "public"."workshop_access" to "authenticated";

grant delete on table "public"."workshop_access" to "service_role";

grant insert on table "public"."workshop_access" to "service_role";

grant references on table "public"."workshop_access" to "service_role";

grant select on table "public"."workshop_access" to "service_role";

grant trigger on table "public"."workshop_access" to "service_role";

grant truncate on table "public"."workshop_access" to "service_role";

grant update on table "public"."workshop_access" to "service_role";

grant delete on table "public"."writing_workshops" to "anon";

grant insert on table "public"."writing_workshops" to "anon";

grant references on table "public"."writing_workshops" to "anon";

grant select on table "public"."writing_workshops" to "anon";

grant trigger on table "public"."writing_workshops" to "anon";

grant truncate on table "public"."writing_workshops" to "anon";

grant update on table "public"."writing_workshops" to "anon";

grant delete on table "public"."writing_workshops" to "authenticated";

grant insert on table "public"."writing_workshops" to "authenticated";

grant references on table "public"."writing_workshops" to "authenticated";

grant select on table "public"."writing_workshops" to "authenticated";

grant trigger on table "public"."writing_workshops" to "authenticated";

grant truncate on table "public"."writing_workshops" to "authenticated";

grant update on table "public"."writing_workshops" to "authenticated";

grant delete on table "public"."writing_workshops" to "service_role";

grant insert on table "public"."writing_workshops" to "service_role";

grant references on table "public"."writing_workshops" to "service_role";

grant select on table "public"."writing_workshops" to "service_role";

grant trigger on table "public"."writing_workshops" to "service_role";

grant truncate on table "public"."writing_workshops" to "service_role";

grant update on table "public"."writing_workshops" to "service_role";


  create policy "public_presences_all"
  on "public"."presences"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "segments_all_public"
  on "public"."segments"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "delete_workshop_access_public"
  on "public"."workshop_access"
  as permissive
  for delete
  to public
using (true);



  create policy "insert_workshop_access_public"
  on "public"."workshop_access"
  as permissive
  for insert
  to public
with check (true);



  create policy "select_workshop_access_public"
  on "public"."workshop_access"
  as permissive
  for select
  to public
using (true);



  create policy "update_workshop_access_public"
  on "public"."workshop_access"
  as permissive
  for update
  to public
using (true)
with check (true);



  create policy "insert_writing_workshops_all"
  on "public"."writing_workshops"
  as permissive
  for insert
  to public
with check (true);



  create policy "select_writing_workshops_public"
  on "public"."writing_workshops"
  as permissive
  for select
  to public
using (true);



  create policy "update_writing_workshops_all"
  on "public"."writing_workshops"
  as permissive
  for update
  to public
using ((status = ANY (ARRAY['draft'::text, 'published'::text])))
with check ((status = ANY (ARRAY['draft'::text, 'published'::text])));



